Reference two Convenience contexts from json-ld.org
json-ld/yaml-ld pull request #106
Opened 2023-07-01 12:13 UTC by anatoly-scherbakov

2023-07-11 19:32 UTC, gkellogg requested changes
The location of the convenience context should be `https://json-ld.org/context/yaml-ld.jsonld`, or something located in  `https://json-ld.org/context/`. The rawgithubcontent is not necessary if referencing this, but a PR to https://github.com/json-ld/json-ld.org to add the context there is necessary.

Also, I would avoid saying "Unfortunately". Perhaps, "Note that ... due to standard JSON-LD processing requirements.

2023-07-12 20:19 UTC, TallTed commented
Please change this PR title from `#94 Reference two Convenience contexts from json-ld.org` to `Reference two Convenience contexts from json-ld.org (for issue #94)`, to reduce confusion when viewing PR/issue lists.

2023-07-21 19:57 UTC, anatoly-scherbakov commented
@gkellogg I will be able to merge the whole chain if this PR is okay.

2023-07-21 21:47 UTC, gkellogg reviewed
I merged both context in json-ld.org. But, we might want to have a couple of examples using `convenience.jsonld` and `dollar-convenience.jsonld` contexts.

2023-07-21 21:47 UTC, gkellogg commented on spec/index.html
> +          <a href="https://json-ld.org/contexts/dollar-convenience.jsonld"><code>$convenience.jsonld</code></a>
Should probably be named based on the actual filename.

```suggestion
          <a href="https://json-ld.org/contexts/dollar-convenience.jsonld"><code> dollar-convenience.jsonld </code></a>
```

2023-07-21 21:49 UTC, merged