Bug fixes in Examples (PR #5 for issue #94)
json-ld/yaml-ld pull request #112
Opened 2023-07-23 05:28 UTC by anatoly-scherbakov

- #94 Make sure examples are valid YAML-LD
- #94 Correct links to example files
- #94 Correct Convenience context example

2023-08-12 19:29 UTC, anatoly-scherbakov commented
@gkellogg please check this out when you have a moment :slightly_smiling_face:

2023-08-13 19:45 UTC, gkellogg requested changes
I suggested using relative links for yaml files. If there is a rendering issue, this might be addressed differently.

2023-08-13 19:45 UTC, gkellogg commented on spec/index.html
> +      <a href="https://github.com/json-ld/yaml-ld/blob/main/spec/data/spec.yaml" target="_blank">
It's cleaner to keep these references as relative to the spec, so when they're published, they show up properly. That would make it `<a href="data/spec.yaml">...</a>`.

2023-08-16 20:48 UTC, anatoly-scherbakov commented
Done so, — but it would seem it does not render. For instance: https://pr-preview.s3.amazonaws.com/json-ld/yaml-ld/pull/data/spec.yaml does not work.

2023-08-16 22:22 UTC, gkellogg commented
> Done so, — but it would seem it does not render. For instance: https://pr-preview.s3.amazonaws.com/json-ld/yaml-ld/pull/data/spec.yaml does not work.

PR Preview doesn't have access to associated files, but you can see them via [GitHack](https://raw.githack.com/json-ld/yaml-ld/issue-94-convenience-contexts-examples/spec/index.html). This better reflects how the spec will render when merged.

2023-08-16 22:22 UTC, gkellogg approved these changes

2023-08-17 07:35 UTC, merged