(closes #119) Introduce `extractAllScripts` flag to handle YAML streams
json-ld/yaml-ld pull request #133
Opened 2024-02-18 21:02 UTC by anatoly-scherbakov

- #131 Ensure `web` directory exists after the repo is cloned
- #131 Test `<script>` tag with two YAML-LD docs in it
- #131 Add `Embedding YAML-LD in HTML Documents` section to the spec
- #131 Specify & test the dedent procedure for YAML-LD blocks
- #131 Ensure that the leading empty lines of the YAML-LD block are skipped when dedenting
- change errant comma to period
- Move the Streams chapter
- Add tests for YAML Streams
- Document support for YAML streams
- Fix the link

2024-02-18 22:21 UTC, gkellogg approved these changes

2024-02-21 17:50 UTC, TallTed requested changes
small things

2024-02-21 17:50 UTC, TallTed commented on spec/index.html
> +      A conformant YAML-LD specification MUST also take this flag in account
```suggestion
      A conformant YAML-LD specification MUST take this flag into account
```

2024-02-21 17:50 UTC, TallTed commented on spec/index.html
> +        If the flag is `true`, the <a>YAML stream</a> is considered an array, and each document in it is an item in that array, even if there is only one document in the stream;
```suggestion
        If the flag is `true`, the <a>YAML stream</a> is considered an array,
        and each document in it is an item in that array, even if there is
        only one document in the stream;
```

2024-02-21 19:13 UTC, TallTed approved these changes

2024-04-03 20:04 UTC, gkellogg commented
The JSON-LD WG discussed this and decided that work can proceed on the editor's draft, so this can be merged after reconciled.

2024-04-04 18:06 UTC, merged