list 2 main YAML features: superset of JSON, yet human-readable
json-ld/yaml-ld pull request #134
Opened 2024-04-02 08:37 UTC by VladimirAlexiev

2024-04-02 08:40 UTC, VladimirAlexiev commented
The precise preview link is https://pr-preview.s3.amazonaws.com/json-ld/yaml-ld/134/efd92b8...VladimirAlexiev:67f79de.html#json-vs-yaml .
Wow @gkellogg this is immensely useful!

2024-04-02 10:59 UTC, anatoly-scherbakov approved these changes
Approving; but I do not think we can merge now, can we? We should wait till WG is re-chartered to continue work on the spec.

2024-04-02 10:59 UTC, anatoly-scherbakov commented on spec/index.html
> +        YAML is more flexible than JSON, as illustrated by the comparison table below.</p>
```suggestion
        But YAML offers a number of extra features, chief amongst which is human readability due to the ability to use minimal punctuation.</p>
        <p>YAML is more flexible than JSON, as illustrated by the comparison table below.</p>
```

Perhaps these could be on separate lines.

2024-04-02 10:59 UTC, anatoly-scherbakov commented on spec/data/json-vs-yaml.yaml
> +        prov:wasDerivedFrom: YAML#chapter-8-block-style-productions
Great addition! I did not think of highlighting this separation of flow vs block syntax which YAML supports.

2024-04-03 20:05 UTC, gkellogg commented
The JSON-LD WG discussed this and decided that work can proceed on the editor's draft, so this can be merged.

2024-04-04 17:13 UTC, TallTed requested changes
minor language and punctuation

2024-04-04 17:13 UTC, TallTed commented on spec/index.html
>        <p>YAML is a superset of JSON, i.e. every valid JSON document is also a valid YAML document.
```suggestion
      <p>YAML is a superset of JSON, i.e., every valid JSON document is also a valid YAML document.
```

2024-04-04 17:13 UTC, TallTed commented on spec/index.html
> +        But YAML offers a number of extra features, chief amongst which is human readability due to the ability to use minimal punctuation.</p>
```suggestion
        YAML also offers a number of extra features, chief amongst which is improved human readability due to the ability to use minimal punctuation.</p>
```

2024-04-04 17:42 UTC, anatoly-scherbakov commented
@VladimirAlexiev I apologize: I reviewed, and committed, changes by @TallTed did not noticing that they were to a PR that is not mine.

2024-04-05 03:16 UTC, TallTed approved these changes
lgtm

2024-04-08 17:28 UTC, gkellogg approved these changes

2024-04-08 22:44 UTC, davidlehn commented on spec/index.html
> +        <p>YAML is more flexible than JSON, as illustrated by the comparison table below.</p>
Fix indent.
```suggestion
      <p>YAML is more flexible than JSON, as illustrated by the comparison table below.</p>
```

2024-05-11 17:11 UTC, anatoly-scherbakov commented
@VladimirAlexiev would you be open to merging this PR, or maybe you wish to add more changes?

2024-06-08 11:03 UTC, anatoly-scherbakov commented
I think I will boldly go and merge :)

2024-06-08 11:03 UTC, merged