#73 How to read this document
json-ld/yaml-ld pull request #80
Opened 2022-08-27 19:55 UTC by anatoly-scherbakov

2022-08-27 22:04 UTC, TallTed requested changes

2022-08-27 22:04 UTC, TallTed commented on spec/index.html
> +            in YAML-LD format. Such documents can be:
```suggestion
            in YAML-LD format. Such documents can be &mdash;
```

2022-08-27 22:04 UTC, TallTed commented on spec/index.html
> +              <li>published on the Web for human and machine consumption.</li>
```suggestion
              <li>consumed by programming systems capable of understanding YAML-LD</li>
              <li>transformed with JSON-LD framing algorithms</li>
              <li>published on the Web for human and machine consumption</li>
```

2022-08-27 22:04 UTC, TallTed commented on spec/index.html
> +            might be beneficial. <a href="#primer">YAML-LD Primer</a> is meant as a gentle introduction
```suggestion
            might be beneficial. The <a href="#primer">YAML-LD Primer</a> is meant as a gentle introduction
```

2022-08-27 22:04 UTC, TallTed commented on spec/index.html
> +        computer science.
```suggestion
        This document is meant as a gentle introduction to YAML-LD for software developers and IT
        professionals as well as professionals in domains other than
        computer science.
```

2022-08-27 23:56 UTC, gkellogg commented
> Introduce the `How to read this document` section and a stub for Primer section as per #73.
> 
> @juusoautiosalo fyi :) For some reason I cannot request review from you.

Juuso needs to be added as a contributor to the repository, which I can take care of.

2022-08-28 10:26 UTC, anatoly-scherbakov commented on spec/index.html
> +          <strong>Software developers</strong> who want to:
@TallTed thank you for the review! But I am not exactly clear why you propose to replace `:` → `—` here? I was accustomed to having `:` in such places.

2022-08-28 10:27 UTC, anatoly-scherbakov commented on spec/index.html
> +            <li>generate or consume Linked Data, an RDF Graph, or an RDF Dataset in a YAML syntax.</li>
@TallTed the same question here: I was accustomed to see commas on such bullet lists.

Is there perhaps a W3C English style guide?

2022-08-28 18:04 UTC, gkellogg commented on spec/index.html
> +          <strong>Software developers</strong> who want to:
I have to say, as a native speaker, this is a bit mysterious to me, as well. There's a useful [writing guide](https://writingcenter.unc.edu/tips-and-tools/semi-colons-colons-and-dashes/) with the following statement:

> 1. To set off material for emphasis. Think of dashes as the opposite of parentheses. Where parentheses indicate that the reader should put less emphasis on the enclosed material, dashes indicate that the reader should pay more attention to the material between the dashes. ...

I'd certainly like to hear @TallTed's reasoning for these cases, though. I generally trust his sense of these things.

2022-08-28 18:07 UTC, gkellogg approved these changes
This is an important piece, thanks for adding. I support @TallTed's suggested changes. I am a bit suspect that non-IT professionals can effectively make use of this without also understanding the core principles of JSON-LD.

2022-08-28 22:10 UTC, TallTed commented on spec/index.html
> +          <strong>Software developers</strong> who want to:
Basically, colons should only follow full sentences, which "Software developers who want to" is not. Typically, rephrasing to include "the following" or similar allows the colon to be used — but "Software developers" is already the object of a preceding sentence, so this (as well as the other) would require additional, more complicated rephrasing. Ending a phrase (an incomplete sentence) that leads into bullets with an em-dash is generally accepted as an alternative.

2022-08-28 22:19 UTC, TallTed commented on spec/index.html
> +            <li>generate or consume Linked Data, an RDF Graph, or an RDF Dataset in a YAML syntax.</li>
There is a [W3C manual of style](https://www.w3.org/Guide/manual-of-style/), but it's largely a handwave to each author'a/editor's own copy/ies of _The Chicago Manual of Style_ and/or _The Gregg Reference Manual_.  I can't cite my copies of these as they are in uncataloged boxes which have not yet been unpacked from my latest move.  I might not be keeping to the letter of these guides, either, as I have largely developed my editorial voice as "what works best for my audience," where that audience is the eventual readers of this document, not so much the other contributors thereto.

Generally speaking, I find that list items that are short (single words, small phrases) should not be terminally punctuated, and every item in that list should be kept short. Longer list items that contain full sentences may be terminally punctuated, but should then also be initially capitalized, and every item in that list should be a full sentence. Neither of these is iron-clad, but work well in general.

2022-08-29 05:18 UTC, merged